apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  labels:
    app: product-service
  namespace: docker-kubernetes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: maikergonzales/product-service:v1
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/product_service_db
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  key: username_password
                  name: mysql-secrets
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: root_password
                  name: mysql-secrets
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  labels:
    app: product-service
  namespace: docker-kubernetes
spec:
  selector:
    app: product-service
  ports:
    - port: 8080
  type: LoadBalancer